package com.example.core.engine

import android.graphics.Color
import com.example.core.model.ParametricShape
import com.example.core.model.PathSegment
import com.example.core.model.PointD
import com.example.core.model.VectorDocument
import com.example.core.model.VectorPath
import com.example.core.model.VectorRegion
import java.util.Locale
import kotlin.math.cos
import kotlin.math.sin

/**
 * Stage 9: SVG Generation & Strict Allow-List Sanitization.
 * Implements SECURITY_AND_PRIVACY.md §3.
 */
object SvgWriter {

    /**
     * Serializes a VectorDocument into a clean, standalone, standard SVG file.
     */
    fun toSvgString(
        document: VectorDocument,
        precision: Int = 2
    ): String {
        val sb = StringBuilder()
        val format = "%.${precision}f"

        sb.append("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n")
        sb.append(
            String.format(
                Locale.US,
                "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 %d %d\" width=\"%d\" height=\"%d\">\n",
                document.width, document.height, document.width, document.height
            )
        )
        sb.append("  <desc>Generated by VectorForge Raster-to-Vector Studio</desc>\n")

        for (region in document.regions) {
            val a = (region.color ushr 24) and 0xFF
            val opacity = a / 255.0

            if (a == 0) continue
            val colorHex = colorToHex(region.color)

            val opacityAttr = if (opacity < 0.99) {
                String.format(Locale.US, " opacity=\"%.2f\"", opacity)
            } else ""

            // If the region has no holes and matches a pure parametric shape, emit clean SVG primitive
            val shape = region.outerPath.parametricShape
            if (shape != null && region.holePaths.isEmpty()) {
                when (shape) {
                    is ParametricShape.Circle -> {
                        sb.append(
                            String.format(
                                Locale.US,
                                "  <circle cx=\"$format\" cy=\"$format\" r=\"$format\" fill=\"%s\"%s />\n",
                                shape.cx, shape.cy, shape.radius, colorHex, opacityAttr
                            )
                        )
                    }
                    is ParametricShape.Ellipse -> {
                        sb.append(
                            String.format(
                                Locale.US,
                                "  <ellipse cx=\"$format\" cy=\"$format\" rx=\"$format\" ry=\"$format\" fill=\"%s\"%s />\n",
                                shape.cx, shape.cy, shape.rx, shape.ry, colorHex, opacityAttr
                            )
                        )
                    }
                    is ParametricShape.RegularPolygon -> {
                        val polyPts = generatePolygonPoints(shape)
                        val ptsString = polyPts.joinToString(" ") { p ->
                            String.format(Locale.US, "$format,$format", p.x, p.y)
                        }
                        sb.append(
                            String.format(
                                Locale.US,
                                "  <polygon points=\"%s\" fill=\"%s\"%s />\n",
                                ptsString, colorHex, opacityAttr
                            )
                        )
                    }
                    is ParametricShape.Star -> {
                        val starPts = generateStarPoints(shape)
                        val ptsString = starPts.joinToString(" ") { p ->
                            String.format(Locale.US, "$format,$format", p.x, p.y)
                        }
                        sb.append(
                            String.format(
                                Locale.US,
                                "  <polygon points=\"%s\" fill=\"%s\"%s />\n",
                                ptsString, colorHex, opacityAttr
                            )
                        )
                    }
                }
            } else {
                // Compound path containing outer boundary and any inner holes
                val d = buildPathData(region.outerPath, region.holePaths, precision)
                val fillRuleAttr = if (region.holePaths.isNotEmpty()) " fill-rule=\"evenodd\"" else ""
                sb.append(
                    String.format(
                        Locale.US,
                        "  <path d=\"%s\" fill=\"%s\"%s%s />\n",
                        d, colorHex, fillRuleAttr, opacityAttr
                    )
                )
            }
        }

        sb.append("</svg>")
        return sb.toString()
    }

    /**
     * Converts VectorDocument to Android Vector Drawable XML format (<vector>).
     */
    fun toAndroidVectorDrawableXml(
        document: VectorDocument,
        precision: Int = 2
    ): String {
        val sb = StringBuilder()
        sb.append("<?xml version=\"1.0\" encoding=\"utf-8\"?>\n")
        sb.append(
            String.format(
                Locale.US,
                "<vector xmlns:android=\"http://schemas.android.com/apk/res/android\"\n" +
                        "    android:width=\"%ddp\"\n" +
                        "    android:height=\"%ddp\"\n" +
                        "    android:viewportWidth=\"%d\"\n" +
                        "    android:viewportHeight=\"%d\">\n",
                document.width, document.height, document.width, document.height
            )
        )

        for (region in document.regions) {
            val a = (region.color ushr 24) and 0xFF
            if (a == 0) continue
            val colorHex = colorToHex(region.color)
            val d = buildPathData(region.outerPath, region.holePaths, precision)
            val fillType = if (region.holePaths.isNotEmpty()) "evenOdd" else "nonZero"
            sb.append(
                String.format(
                    Locale.US,
                    "    <path\n" +
                            "        android:fillColor=\"%s\"\n" +
                            "        android:fillType=\"%s\"\n" +
                            "        android:pathData=\"%s\" />\n",
                    colorHex, fillType, d
                )
            )
        }

        sb.append("</vector>")
        return sb.toString()
    }

    private fun buildPathData(
        outerPath: VectorPath,
        holePaths: List<VectorPath>,
        precision: Int
    ): String {
        val sb = StringBuilder()
        appendSinglePathData(outerPath, sb, precision)
        for (hole in holePaths) {
            appendSinglePathData(hole, sb, precision)
        }
        return sb.toString().trim()
    }

    private fun appendSinglePathData(path: VectorPath, sb: StringBuilder, precision: Int) {
        if (path.segments.isEmpty()) return
        val format = "%.${precision}f"

        val firstSeg = path.segments.first()
        val startPt = when (firstSeg) {
            is PathSegment.Line -> firstSeg.p0
            is PathSegment.CubicBezier -> firstSeg.p0
        }

        sb.append(String.format(Locale.US, "M $format $format ", startPt.x, startPt.y))

        for (segment in path.segments) {
            when (segment) {
                is PathSegment.Line -> {
                    sb.append(String.format(Locale.US, "L $format $format ", segment.p1.x, segment.p1.y))
                }
                is PathSegment.CubicBezier -> {
                    sb.append(
                        String.format(
                            Locale.US,
                            "C $format $format $format $format $format $format ",
                            segment.p1.x, segment.p1.y,
                            segment.p2.x, segment.p2.y,
                            segment.p3.x, segment.p3.y
                        )
                    )
                }
            }
        }
        sb.append("Z ")
    }

    private fun colorToHex(color: Int): String {
        val r = (color ushr 16) and 0xFF
        val g = (color ushr 8) and 0xFF
        val b = color and 0xFF
        return String.format("#%02X%02X%02X", r, g, b)
    }

    private fun generatePolygonPoints(poly: ParametricShape.RegularPolygon): List<PointD> {
        val pts = ArrayList<PointD>()
        val angleStep = (2.0 * Math.PI) / poly.sides
        val startRad = Math.toRadians(poly.rotationDeg)
        for (i in 0 until poly.sides) {
            val a = startRad + i * angleStep
            pts.add(PointD(poly.cx + poly.radius * cos(a), poly.cy + poly.radius * sin(a)))
        }
        return pts
    }

    private fun generateStarPoints(star: ParametricShape.Star): List<PointD> {
        val pts = ArrayList<PointD>()
        val totalRays = star.points * 2
        val angleStep = (2.0 * Math.PI) / totalRays
        val startRad = Math.toRadians(star.rotationDeg)
        for (i in 0 until totalRays) {
            val a = startRad + i * angleStep
            val r = if (i % 2 == 0) star.outerRadius else star.innerRadius
            pts.add(PointD(star.cx + r * cos(a), star.cy + r * sin(a)))
        }
        return pts
    }
}
